### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by sh1eda** [elevenvac/apptime-desktop#1]
app.whenReady().then(createWindow);
    ^

TypeError: Cannot read property 'whenReady' of undefined
    at Object.<anonymous> (D:\Discord\apptime-desktop-3.1.0\main.js:47:5)

**Comment by elevenski** [comment]
**i tried but i didn't see any error:**

i downloaded it without changing anything,
i used `npm i`  & `npm start` commands respectively,
app opened successfully.

**Comment by elevenski** [comment]
long time
